purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8727599
  brandStrength: 0.03521076589822769
  lightness: 0.9256635
  brandColors: []
  rhythmicContrast: 0.115672
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: GemmaZoeJonesArt
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.265233
layout_spectrum: 0.9444444
